# Related Datasets and Research Resources

## Overview

The Turkish Delight Corpus (TDC) is part of a broader ecosystem of open datasets and computational resources developed for Turkish makam music research.

Although this book primarily focuses on the computational analysis of **SymbTr v3.0**, several complementary datasets and research projects have been developed to support phrase segmentation, melodic analysis, symbolic music processing, and Music Information Retrieval (MIR).

This chapter introduces these related datasets together with representative research studies that provide additional context for computational musicology and machine learning applications in Turkish makam music.

## The Turkish Makam Research Ecosystem

Computational research on Turkish makam music has evolved from symbolic score collections to phrase-level datasets, melodic annotations, and machine learning applications.

The Music Technology Group (MTG), Universitat Pompeu Fabra (UPF), has played a leading role in developing openly available datasets that enable reproducible computational musicology research.

Together, these resources provide a comprehensive ecosystem for symbolic music analysis, phrase segmentation, similarity analysis, clustering, visualization, and machine learning.

In [1]:
import pandas as pd

datasets = pd.DataFrame({
    "Dataset":[
        "SymbTr v3.0",
        "Turkish Makam Symbolic Phrase Dataset",
        "Turkish Makam Melodic Phrase Dataset"
    ],
    "Representation":[
        "Complete symbolic scores",
        "Phrase-level symbolic annotations",
        "Melodic phrase annotations"
    ],
    "Primary Application":[
        "Computational Musicology",
        "Phrase Segmentation",
        "Melodic Analysis"
    ],
    "Institution":[
        "MTG-UPF",
        "MTG-UPF",
        "MTG-UPF"
    ]
})

datasets

,Dataset,Representation,Primary Application,Institution
0,SymbTr v3.0,Complete symbolic scores,Computational Musicology,MTG-UPF
1,Turkish Makam Symbolic Phrase Dataset,Phrase-level symbolic annotations,Phrase Segmentation,MTG-UPF
2,Turkish Makam Melodic Phrase Dataset,Melodic phrase annotations,Melodic Analysis,MTG-UPF

## Unified Computational Workflow Across Public Turkish Makam Music Datasets

One of the primary contributions of the Turkish Delight Corpus is the demonstration that a single computational workflow can be applied consistently across multiple public symbolic Turkish makam music datasets. Although these datasets differ in scope, annotation level, and musical granularity, they share a common analytical pipeline that enables reproducible statistical analysis, visualization, dimensionality reduction, clustering, similarity analysis, and comparative computational studies.

| Computational Analysis | SymbTr v3.0 | Symbolic Phrase Dataset | Melodic Phrase Dataset |
|-------------------------|:-----------:|:-----------------------:|:----------------------:|
| Dataset exploration | ✓ | ✓ | ✓ |
| Summary statistics | ✓ | ✓ | ✓ |
| Metadata analysis | ✓ | ✓ | ✓ |
| Data visualization | ✓ | ✓ | ✓ |
| Principal Component Analysis (PCA) | ✓ | ✓ | ✓ |
| Clustering analysis | ✓ | ✓ | ✓ |
| Similarity analysis | ✓ | ✓ | ✓ |
| Comparative analysis | ✓ | ✓ | ✓ |

The table shows that the proposed workflow is largely dataset-independent and can be transferred across symbolic music collections with minimal modifications. This unified framework facilitates reproducible computational musicology research and establishes a common analytical basis for future studies on Turkish makam music.

## Unified Workflow Diagram

```{mermaid}
flowchart TD

TDC[Turkish Delight Corpus]

S1[SymbTr v3.0]
S2[Symbolic Phrase Dataset]
S3[Melodic Phrase Dataset]

W[Unified Computational Workflow]

A1[Dataset Exploration]
A2[Summary Statistics]
A3[Visualization]
A4[PCA]
A5[Clustering]
A6[Similarity Analysis]
A7[Comparative Analysis]

TDC --> S1
TDC --> S2
TDC --> S3

S1 --> W
S2 --> W
S3 --> W

W --> A1
W --> A2
W --> A3
W --> A4
W --> A5
W --> A6
W --> A7
```

## SymbTr v3.0

SymbTr v3.0 is the primary symbolic corpus used throughout this book.

The dataset contains approximately 3,000 symbolic scores representing a wide variety of Turkish makams, usuls, musical forms, and composers.

Throughout this tutorial, SymbTr serves as the foundation for exploratory data analysis, statistical analysis, visualization, dimensionality reduction, clustering, and comparative computational musicology studies.

## Turkish Makam Symbolic Phrase Dataset

The Turkish Makam Symbolic Phrase Dataset extends the SymbTr corpus by providing manually annotated phrase boundaries created by expert musicians.

Instead of complete musical works, the dataset represents phrase-level symbolic units, enabling research on phrase similarity, phrase segmentation, symbolic music retrieval, and computational analysis of melodic structures.

The dataset has become an important benchmark for phrase-based computational musicology.

## Turkish Makam Melodic Phrase Dataset

The Turkish Makam Melodic Phrase Dataset provides manually annotated melodic phrase boundaries extracted from symbolic music scores.

These annotations facilitate research on melodic segmentation, melodic pattern discovery, phrase classification, and machine learning approaches for symbolic music analysis.

Together with the Symbolic Phrase Dataset, it complements the SymbTr corpus by supporting phrase-level computational investigations.

## Relationship Between the Datasets

Although these datasets are closely related, they represent different structural levels of Turkish makam music.

While SymbTr provides complete symbolic scores, the phrase datasets focus on localized musical structures that enable more detailed computational analyses.

Together they establish a unified framework for computational musicology research.

In [4]:
relationship = pd.DataFrame({
    "Dataset":[
        "SymbTr v3.0",
        "Symbolic Phrase Dataset",
        "Melodic Phrase Dataset"
    ],
    "Analysis Level":[
        "Complete Score",
        "Phrase",
        "Melodic Phrase"
    ],
    "Typical Applications":[
        "EDA, Statistics, Clustering",
        "Phrase Segmentation",
        "Melodic Analysis"
    ]
})

relationship

                   Dataset  Analysis Level         Typical Applications
0              SymbTr v3.0  Complete Score  EDA, Statistics, Clustering
1  Symbolic Phrase Dataset          Phrase          Phrase Segmentation
2   Melodic Phrase Dataset  Melodic Phrase             Melodic Analysis

## Representative Research Topics

The datasets presented in this chapter have supported research in numerous areas of computational musicology, including

- Symbolic music processing
- Phrase segmentation
- Melodic similarity analysis
- Pattern discovery
- Music Information Retrieval (MIR)
- Machine learning
- Deep learning
- Computational musicology
- Clustering
- Dimensionality reduction

## Why Turkish Delight Corpus?

Unlike conventional dataset repositories, the Turkish Delight Corpus combines openly available datasets with fully reproducible computational workflows.

By integrating exploratory data analysis, statistical methods, visualization, machine learning, clustering, and comparative analysis into a unified Jupyter Book, the project serves both as an educational resource and as a reproducible research platform.

The Turkish Delight Corpus therefore complements existing Turkish makam music datasets by demonstrating not only **what** data are available but also **how** they can be analyzed using modern computational techniques.

## Representative Publications

The following publications constitute the core literature related to the datasets introduced in this chapter. These studies describe the development of symbolic corpora, phrase-level annotations, melodic segmentation, and computational approaches for Turkish makam music analysis.

In [5]:
import pandas as pd

publications = pd.DataFrame({
    "Year":[
        2012,
        2014,
        2014
    ],
    "Topic":[
        "SymbTr Corpus",
        "Symbolic Phrase Dataset",
        "Melodic Phrase Dataset"
    ],
    "Research Area":[
        "Symbolic Music Corpus",
        "Phrase Segmentation",
        "Melodic Analysis"
    ],
    "Institution":[
        "MTG-UPF",
        "MTG-UPF",
        "MTG-UPF"
    ]
})

publications

   Year                    Topic          Research Area Institution
0  2012            SymbTr Corpus  Symbolic Music Corpus     MTG-UPF
1  2014  Symbolic Phrase Dataset    Phrase Segmentation     MTG-UPF
2  2014   Melodic Phrase Dataset       Melodic Analysis     MTG-UPF

## Computational Research Pipeline

The datasets presented throughout this chapter support different stages of computational musicology.

## Computational Research Pipeline

```{mermaid}
flowchart LR

A[SymbTr v3.0]
B[Symbolic Phrase Dataset]
C[Melodic Phrase Dataset]

D[Exploratory Data Analysis]
E[Statistical Analysis]
F[Visualization]
G[Machine Learning]
H[Computational Musicology]

A --> D
A --> E
A --> F
A --> G

B --> G
C --> G

G --> H
```

## Future Research Directions

The increasing availability of open symbolic music datasets enables new research directions in computational musicology.

Potential future research topics include

- Foundation models for symbolic music
- Transformer-based makam analysis
- Graph neural networks
- Multimodal audio–symbolic learning
- Large Language Models for music understanding
- Interactive computational musicology
- Explainable Artificial Intelligence (XAI)
- Human-centered Music Information Retrieval

Project

Description

Year

Dataset

Link

Title

Authors

Venue

Year

DOI

## Representative Publications

The following publications represent some of the most influential studies related to the datasets presented in this chapter. Together, they provide the methodological and scientific foundations for computational analysis of Turkish makam music.

In [3]:
import pandas as pd

publications = pd.DataFrame([
    {
        "Title": "SymbTr: A Repository of Computationally Readable Symbolic Music Data for Turkish Makam Music",
        "Authors": "Sertan Şentürk et al.",
        "Venue": "ISMIR",
        "Year": 2012,
        "DOI": "-"
    },
    {
        "Title": "A Symbolic Phrase Dataset for Turkish Makam Music",
        "Authors": "Sertan Şentürk et al.",
        "Venue": "FMA",
        "Year": 2014,
        "DOI": "-"
    },
    {
        "Title": "An Annotated Melodic Phrase Dataset for Turkish Makam Music",
        "Authors": "Sertan Şentürk et al.",
        "Venue": "Journal / Dataset",
        "Year": 2014,
        "DOI": "-"
    }
])

publications

,Title,Authors,Venue,Year,DOI
0,SymbTr: A Repository of Computationally Readab...,Sertan Şentürk et al.,ISMIR,2012,-
1,A Symbolic Phrase Dataset for Turkish Makam Music,Sertan Şentürk et al.,FMA,2014,-
2,An Annotated Melodic Phrase Dataset for Turkis...,Sertan Şentürk et al.,Journal / Dataset,2014,-

## Research Timeline

The development of computational resources for Turkish makam music has progressed from symbolic score collections toward increasingly detailed phrase-level annotations and advanced computational analysis techniques.

The timeline below summarizes the evolution of major datasets and research directions.

In [4]:
timeline = pd.DataFrame({
    "Year":[2012,2014,2014,2016,2020,2025],
    "Milestone":[
        "SymbTr Corpus",
        "Symbolic Phrase Dataset",
        "Melodic Phrase Dataset",
        "Phrase-based Computational Analysis",
        "Machine Learning Applications",
        "Turkish Delight Corpus (TDC)"
    ]
})

timeline

   Year                            Milestone
0  2012                        SymbTr Corpus
1  2014              Symbolic Phrase Dataset
2  2014               Melodic Phrase Dataset
3  2016  Phrase-based Computational Analysis
4  2020        Machine Learning Applications
5  2025         Turkish Delight Corpus (TDC)

## Available Software and Resources

Several open software projects and repositories have been developed to support computational research on Turkish makam music.

These resources complement the datasets presented in this chapter and facilitate reproducible research in Music Information Retrieval (MIR) and computational musicology.

In [5]:
resources = pd.DataFrame({
    "Resource":[
        "SymbTr v3.0",
        "Turkish Makam Symbolic Phrase Segmentation Dataset",
        "Turkish Makam Melodic Phrase Dataset",
        "Turkish Delight Corpus"
    ],
    "Type":[
        "Dataset",
        "Dataset",
        "Dataset",
        "Interactive Jupyter Book"
    ],
    "Main Purpose":[
        "Symbolic score analysis",
        "Phrase segmentation",
        "Melodic phrase analysis",
        "Reproducible computational workflows"
    ]
})

resources

,Resource,Type,Main Purpose
0,SymbTr v3.0,Dataset,Symbolic score analysis
1,Turkish Makam Symbolic Phrase Segmentation Dat...,Dataset,Phrase segmentation
2,Turkish Makam Melodic Phrase Dataset,Dataset,Melodic phrase analysis
3,Turkish Delight Corpus,Interactive Jupyter Book,Reproducible computational workflows

## Open Research Challenges

Despite the availability of several high-quality datasets, numerous research challenges remain in computational analysis of Turkish makam music.

Current challenges include

- automatic phrase segmentation,
- melodic similarity learning,
- explainable machine learning,
- symbolic–audio integration,
- large-scale comparative corpus analysis,
- foundation models for symbolic music,
- multimodal music understanding, and
- reproducible computational workflows.

## Future Research Directions

The Turkish Delight Corpus provides a reproducible computational framework that can be extended in several directions.

Potential future developments include

- Transformer-based symbolic music models
- Graph Neural Networks (GNNs)
- Foundation Models for symbolic music
- Large Language Models (LLMs) for music understanding
- Retrieval-Augmented Generation (RAG) for music archives
- Explainable Artificial Intelligence (XAI)
- Human-centered Music Information Retrieval
- Cross-modal audio–symbolic learning

## Further Reading

Readers interested in computational analysis of Turkish makam music are encouraged to explore the following resources:

- Music Technology Group (MTG), Universitat Pompeu Fabra
- CompMusic Project
- SymbTr GitHub Repository
- Zenodo Dataset Repository
- ISMIR Proceedings
- Transactions of the International Society for Music Information Retrieval (TISMIR)

## Summary

This chapter introduced the principal datasets, research resources, and representative publications that form the computational ecosystem of Turkish makam music.

Together, these resources provide complementary perspectives ranging from complete symbolic scores to phrase-level annotations, enabling research in computational musicology, Music Information Retrieval, machine learning, and symbolic music processing.

The Turkish Delight Corpus builds upon these resources by integrating them into a unified, reproducible, and educational computational framework.

## Core Publications and Datasets

The following publications constitute the core literature describing the datasets and computational resources introduced in this chapter. They provide the methodological foundations for symbolic music processing, phrase segmentation, and computational musicology research on Turkish makam music.

In [12]:
import pandas as pd

publications = pd.DataFrame([
    {
        "Title": "SymbTr: A Repository of Computationally Readable Symbolic Music Data for Turkish Makam Music",
        "Year": 2012,
        "Venue": "ISMIR",
        "Topic": "Symbolic Music Corpus",
        "Resource": "SymbTr v3.0"
    },
    {
        "Title": "A Symbolic Dataset of Turkish Makam Music Phrases",
        "Year": 2014,
        "Venue": "4th International Workshop on Folk Music Analysis (FMA)",
        "Topic": "Phrase Segmentation",
        "Resource": "Phrase Dataset"
    },
    {
        "Title": "Turkish Makam Symbolic Phrase Segmentation Dataset",
        "Year": 2016,
        "Venue": "Zenodo",
        "Topic": "Open Dataset",
        "Resource": "Dataset DOI"
    }
])

publications

,Title,Year,Venue,Topic,Resource
0,SymbTr: A Repository of Computationally Readab...,2012,ISMIR,Symbolic Music Corpus,SymbTr v3.0
1,A Symbolic Dataset of Turkish Makam Music Phrases,2014,4th International Workshop on Folk Music Analy...,Phrase Segmentation,Phrase Dataset
2,Turkish Makam Symbolic Phrase Segmentation Dat...,2016,Zenodo,Open Dataset,Dataset DOI

## Useful Links

The following resources provide direct access to the datasets, software repositories, and project websites discussed throughout this chapter.

| Resource | URL |
|-----------|-----|
| SymbTr GitHub | https://github.com/MTG/SymbTr |
| Turkish Makam Symbolic Phrase Dataset | https://compmusic.upf.edu/node/237 |
| Turkish Makam Melodic Phrase Dataset | https://compmusic.upf.edu/node/236 |
| Phrase Segmentation Dataset (Zenodo) | https://doi.org/10.5281/zenodo.168208 |
| CompMusic Project | https://compmusic.upf.edu |
| Music Technology Group (UPF) | https://www.upf.edu/web/mtg |

## How These Resources Complement the Turkish Delight Corpus

The Turkish Delight Corpus (TDC) does not replace the existing datasets; rather, it complements them by providing a unified and reproducible computational framework.

While previous resources primarily focused on data collection and annotation, TDC emphasizes computational analysis through interactive Jupyter notebooks. The book integrates exploratory data analysis, statistical methods, visualization, dimensionality reduction, clustering, and comparative analyses into a single educational and research-oriented platform.

This integration enables researchers, educators, and students to move seamlessly from accessing symbolic music datasets to performing reproducible computational analyses using modern Python-based workflows.

## Landmark Publications

The following publications represent the core literature that established the symbolic datasets and computational methods used in Turkish makam music research.

These studies introduced the SymbTr corpus, phrase-level datasets, melodic segmentation techniques, and audio-score alignment methodologies that form the foundation of many subsequent computational musicology studies.

In [13]:
import pandas as pd

papers = pd.DataFrame([
    {
        "Year": 2012,
        "Publication": "A Turkish Makam Music Symbolic Database for Music Information Retrieval: SymbTr",
        "Authors": "M. Kemal Karaosmanoğlu",
        "Venue": "ISMIR",
        "Research Topic": "Symbolic Corpus"
    },
    {
        "Year": 2014,
        "Publication": "A Symbolic Dataset of Turkish Makam Music Phrases",
        "Authors": "M. K. Karaosmanoğlu, B. Bozkurt, A. Holzapfel, N. D. Dişiaçık",
        "Venue": "FMA",
        "Research Topic": "Phrase Dataset"
    },
    {
        "Year": 2014,
        "Publication": "Usul and Makam Driven Automatic Melodic Segmentation for Turkish Music",
        "Authors": "B. Bozkurt et al.",
        "Venue": "Journal of New Music Research",
        "Research Topic": "Melodic Segmentation"
    },
    {
        "Year": 2014,
        "Publication": "Linking Scores and Audio Recordings in Makam Music of Turkey",
        "Authors": "S. Şentürk, A. Holzapfel, X. Serra",
        "Venue": "Journal of New Music Research",
        "Research Topic": "Audio–Score Alignment"
    }
])

papers

,Year,Publication,Authors,Venue,Research Topic
0,2012,A Turkish Makam Music Symbolic Database for Mu...,M. Kemal Karaosmanoğlu,ISMIR,Symbolic Corpus
1,2014,A Symbolic Dataset of Turkish Makam Music Phrases,"M. K. Karaosmanoğlu, B. Bozkurt, A. Holzapfel,...",FMA,Phrase Dataset
2,2014,Usul and Makam Driven Automatic Melodic Segmen...,B. Bozkurt et al.,Journal of New Music Research,Melodic Segmentation
3,2014,Linking Scores and Audio Recordings in Makam M...,"S. Şentürk, A. Holzapfel, X. Serra",Journal of New Music Research,Audio–Score Alignment

## Evolution of Turkish Makam Music Research

The development of computational resources for Turkish makam music can be viewed as a progressive evolution.

- **2012:** Introduction of the SymbTr symbolic music corpus.
- **2014:** Release of phrase-level symbolic datasets.
- **2014:** Automatic melodic segmentation using usul and makam information.
- **2014:** Audio–score alignment methodologies.
- **2025:** SymbTr v3.0 expands the corpus to approximately 3,000 symbolic scores and provides additional machine-readable representations.

In [14]:
timeline = pd.DataFrame({
    "Year":[2012,2014,2014,2014,2025],
    "Milestone":[
        "SymbTr introduced",
        "Phrase Dataset",
        "Melodic Phrase Dataset",
        "Audio-Score Alignment",
        "SymbTr v3.0"
    ]
})

timeline

   Year               Milestone
0  2012       SymbTr introduced
1  2014          Phrase Dataset
2  2014  Melodic Phrase Dataset
3  2014   Audio-Score Alignment
4  2025             SymbTr v3.0

## Suggested Reading

Researchers interested in computational Turkish makam music may wish to explore the following topics:

- Symbolic music representation
- Phrase segmentation
- Melodic structure analysis
- Audio–score alignment
- Music Information Retrieval (MIR)
- Machine learning for symbolic music
- Computational musicology
- Cross-cultural music analysis