In [1]:
import pandas as pd
from pathlib import Path

DATA_RAW = Path("../data/raw").resolve()

csv_file = DATA_RAW / "Turkish maqam music pieces in time series format_3000 rows x 365 columns.csv"

df = pd.read_csv(csv_file)

print("Shape:", df.shape)

Shape: (3000, 366)

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Columns: 366 entries, ID to p365
dtypes: float64(363), int64(2), str(1)
memory usage: 8.4 MB

In [3]:
df.describe()

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p356,p357,p358,p359,p360,p361,p362,p363,p364,p365
count,2999.000000,2990.000000,2988.000000,2976.000000,2967.000000,2960.000000,2962.000000,2970.000000,2957.000000,2962.000000,...,2969.000000,2983.000000,2973.000000,2981.000000,2990.000000,2990.000000,2989.000000,2995.000000,3000.000000,3000.000000
mean,324.263421,326.954181,328.303882,328.463710,328.049208,327.873986,327.110736,327.157912,327.070342,327.599932,...,312.734254,311.941669,311.052809,309.993626,308.352174,306.783278,305.166611,303.355259,301.796333,301.575333
std,20.546112,19.820276,19.911993,19.541209,19.857710,20.486100,20.878217,20.654489,21.485569,20.691874,...,17.575706,16.949464,16.767276,16.020403,15.430590,14.669021,13.754262,12.855006,11.696458,11.241402
min,230.000000,230.000000,230.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,...,221.000000,230.000000,230.000000,221.000000,221.000000,230.000000,243.000000,243.000000,230.000000,269.000000
25%,305.000000,313.000000,314.000000,318.000000,318.000000,318.000000,314.000000,313.000000,314.000000,318.000000,...,305.000000,305.000000,305.000000,305.000000,300.000000,296.000000,296.000000,296.000000,296.000000,296.000000
50%,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,...,313.000000,313.000000,310.000000,309.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000
75%,340.000000,344.000000,344.000000,344.000000,340.000000,344.000000,340.000000,340.000000,340.000000,340.000000,...,327.000000,322.000000,318.000000,318.000000,318.000000,313.000000,313.000000,305.000000,305.000000,305.000000
max,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,393.000000,389.000000,...,380.000000,371.000000,371.000000,371.000000,380.000000,380.000000,384.000000,402.000000,402.000000,402.000000

In [7]:
missing_values = df.isnull().sum().sum()

print("Total Missing Values:", missing_values)

missing_percentage = (
    missing_values /
    (df.shape[0] * (df.shape[1]-1))
) * 100

print(f"Missing Percentage: {missing_percentage:.2f}%")

Total Missing Values: 20293
Missing Percentage: 1.85%

In [8]:
df.head()

,ID,p1,p2,p3,p4,p5,p6,p7,p8,p9,...,p356,p357,p358,p359,p360,p361,p362,p363,p364,p365
0,acem--ilahi--duyek--aldanma_dunya--zekai_dede,318.0,318.0,318.0,340.0,340.0,336.0,340.0,340.0,336.0,...,318.0,313.0,313.0,305.0,296.0,318.0,305.0,305.0,305,305
1,acem--ilahi--nimevsat--calabim_bir--haci_bayra...,305.0,305.0,305.0,340.0,340.0,340.0,340.0,340.0,340.0,...,313.0,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305,305
2,acem--kupe--duyek--zulfunu--ahmet_avni_konuk,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305.0,...,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305,305
3,acem--selam--devrikebir--asik-i_ger--huseyin_f...,318.0,340.0,349.0,340.0,340.0,349.0,327.0,313.0,318.0,...,318.0,313.0,305.0,305.0,318.0,318.0,287.0,305.0,287,287
4,acem--seyir--sofyan----sefik_gurmeric,305.0,305.0,305.0,305.0,305.0,305.0,340.0,340.0,340.0,...,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305.0,305,305

In [6]:
print("Missing values:", df.isnull().sum().sum())

Missing values: 20293

In [10]:
X = df.iloc[:,1:]

desc_stats = X.describe()

desc_stats

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p356,p357,p358,p359,p360,p361,p362,p363,p364,p365
count,2999.000000,2990.000000,2988.000000,2976.000000,2967.000000,2960.000000,2962.000000,2970.000000,2957.000000,2962.000000,...,2969.000000,2983.000000,2973.000000,2981.000000,2990.000000,2990.000000,2989.000000,2995.000000,3000.000000,3000.000000
mean,324.263421,326.954181,328.303882,328.463710,328.049208,327.873986,327.110736,327.157912,327.070342,327.599932,...,312.734254,311.941669,311.052809,309.993626,308.352174,306.783278,305.166611,303.355259,301.796333,301.575333
std,20.546112,19.820276,19.911993,19.541209,19.857710,20.486100,20.878217,20.654489,21.485569,20.691874,...,17.575706,16.949464,16.767276,16.020403,15.430590,14.669021,13.754262,12.855006,11.696458,11.241402
min,230.000000,230.000000,230.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,...,221.000000,230.000000,230.000000,221.000000,221.000000,230.000000,243.000000,243.000000,230.000000,269.000000
25%,305.000000,313.000000,314.000000,318.000000,318.000000,318.000000,314.000000,313.000000,314.000000,318.000000,...,305.000000,305.000000,305.000000,305.000000,300.000000,296.000000,296.000000,296.000000,296.000000,296.000000
50%,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,...,313.000000,313.000000,310.000000,309.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000
75%,340.000000,344.000000,344.000000,344.000000,340.000000,344.000000,340.000000,340.000000,340.000000,340.000000,...,327.000000,322.000000,318.000000,318.000000,318.000000,313.000000,313.000000,305.000000,305.000000,305.000000
max,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,393.000000,389.000000,...,380.000000,371.000000,371.000000,371.000000,380.000000,380.000000,384.000000,402.000000,402.000000,402.000000

In [11]:
X = df.iloc[:,1:]

print("Global Mean :", X.stack().mean())
print("Global Std  :", X.stack().std())
print("Global Min  :", X.min().min())
print("Global Max  :", X.max().max())

Global Mean : 325.293183165272
Global Std  : 22.45477095024957
Global Min  : 0.0
Global Max  : 402.0

In [12]:
print("Global Median :", X.stack().median())

Global Median : 327.0

In [13]:
summary = pd.DataFrame({
    "Metric": [
        "Number of Pieces",
        "Time Steps",
        "Missing Values",
        "Global Mean",
        "Global Median",
        "Global Std",
        "Global Min",
        "Global Max"
    ],
    "Value": [
        len(df),
        X.shape[1],
        df.isnull().sum().sum(),
        round(X.stack().mean(),2),
        round(X.stack().median(),2),
        round(X.stack().std(),2),
        X.min().min(),
        X.max().max()
    ]
})

summary

             Metric     Value
0  Number of Pieces   3000.00
1        Time Steps    365.00
2    Missing Values  20293.00
3       Global Mean    325.29
4     Global Median    327.00
5        Global Std     22.45
6        Global Min      0.00
7        Global Max    402.00